name: sas_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  sensors_plus: ^6.0.1
  geolocator: ^9.0.2
  image_picker: ^0.8.7+4
  shared_preferences: ^2.3.2
  home_widget: ^0.7.0
  camera: ^0.11.0+1
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
